### ISSUE TITLE
Test new block templates and special html classes

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/default#39]
Default now comes with the following block templates and classes, designed to provide more page building  options for attractive landing pages. Test that these block templates and classes display as intended and scale well at both mobile and desktop widths.

# Asset block template: 3-column grid

This template is best used for displaying page links with asset images. It lays the assets out in a 3-column grid for widths greater than 800px, then scales down to 2 for widths greater than 400px, then a single column for anything smaller. 

<img width="1100" alt="image" src="https://github.com/omeka-s-themes/default/assets/606764/ddc8f512-8b3d-49aa-a96c-211f47e9d4aa">

 # Media block template: 2-column cards

This presents media attachments as white cards with the media on the left and metadata on the right, each taking up half the card width. At widths above 800px, it shows as 2 columns. Each card should be a uniform height in its row. This template ignores the vertical vs horizontal layout setting. It looks best with an even number of attachments, each set with a short caption.

<img width="924" alt="image" src="https://github.com/omeka-s-themes/default/assets/606764/ff47a33c-0f27-4555-8c9c-94fbda30e3cd">

# HTML class: "spotlight"

**Available paired classes**: "left-image", "light accent", "dark accent"

This is intended to pair a user-assigned decorative background image inline with text content. The user must set a background image using the block configuration. By default, the background image is aligned to the right. Users can pair this class with "left-image" to move the background image to the left. There are also options to set a single color accent background using "light accent" and "dark accent".

<img width="1090" alt="image" src="https://github.com/omeka-s-themes/default/assets/606764/db6ece56-051b-49f5-985f-8034cced15e9">

<img width="1090" alt="image" src="https://github.com/omeka-s-themes/default/assets/606764/dd990846-b434-43f3-87a7-616982369207">

<img width="1090" alt="image" src="https://github.com/omeka-s-themes/default/assets/606764/cad5eee0-6ea8-4692-9ca0-980841a3830d">

**Comment by allanaaa** [comment]
Assets card looks good and behaves as expected on desktop.

For the media card, it looks good, but should template use maybe grey out the relevant options ("Vertical" and "horizontal" in this case)? Or will that be too hard to implement?

I'm also not getting "half the card width" each - in this case the video thumbnail is taking up most and the text is pushing the box very tall. 
<img width="1341" alt="Screenshot 2024-05-16 at 15 21 15" src="https://github.com/omeka-s-themes/default/assets/28012148/0131cef0-54bc-47fb-937b-ad6f5d0a2ac8">
That was thumbnail large. This is embed media large:
<img width="1326" alt="Screenshot 2024-05-16 at 15 22 36" src="https://github.com/omeka-s-themes/default/assets/28012148/c83d5806-f5e7-4522-96fc-35bcba08e55c">
And embed media medium: 
<img width="1330" alt="Screenshot 2024-05-16 at 15 22 55" src="https://github.com/omeka-s-themes/default/assets/28012148/6b858e0e-e1b9-415e-aa6f-7c9f6cf97f3e">

So nothing seems to be set to 50%.

**Comment by allanaaa** [comment]
How are you calling "light accent" and "dark accent" as classes? light-accent and dark-accent? Or is "accent" one class and "light" or "dark" are others? 

<img width="363" alt="Screenshot 2024-05-16 at 15 52 04" src="https://github.com/omeka-s-themes/default/assets/28012148/03052da5-7820-40af-ba75-a69df5054edc">

**Comment by allanaaa** [comment]
So these are classes meant to be used on an HTML block? Or will they work on any kind of block?

**Comment by kimisgold** [comment]
> How are you calling "light accent" and "dark accent" as classes? light-accent and dark-accent? Or is "accent" one class and "light" or "dark" are others?

Yes sorry, it should be "light-accent" and "dark-accent", used in tandem with the "spotlight" class. They should work with any block, but I've mainly tested it with HTML.

**Comment by kimisgold** [comment]
The 50% width for the asset cards should now be fixed.

**Comment by kimisgold** [comment]
@allanaaa Circling back to this: is there any remaining work to be done before closing this issue?

**Comment by allanaaa** [comment]
The media cards still have some vestigial CSS problems: the first row is set to vertical, and displays well (although there is a weird top-border effect happening?); the second is set to horizontal, and there is a padding difference so the cards aren't top-aligned:

<img width="1207" alt="Screenshot 2024-08-26 at 12 08 39" src="https://github.com/user-attachments/assets/5db8913e-6762-4c06-babf-7c90540940b1">

You can see the top-border problem if you go here and resize the browser width back and forth: 
http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/page/asset-test

I suppose you can't grey out options in the page edit based on whether you select a template, but that CSS should be overriding the vertical/horizontal differences.

**Comment by allanaaa** [comment]
Also, if I've got padding set on the media block, this 30px top and bottom margin shouldn't be there. I'm not sure it ever needs to be there? 

<img width="1269" alt="Screenshot 2024-08-26 at 12 12 59" src="https://github.com/user-attachments/assets/b3ab68fa-0f48-4393-9926-0a3dbdd7d0ec">
<img width="1254" alt="Screenshot 2024-08-26 at 12 13 12" src="https://github.com/user-attachments/assets/1efb0144-f9d6-4ae7-ac45-a641d4959cdb">
<img width="464" alt="Screenshot 2024-08-26 at 12 13 33" src="https://github.com/user-attachments/assets/0287a572-4de7-472d-9b94-d77e4a1e431e">

It's there on the horizontal-set media block too, but it's collapsing.

<img width="1105" alt="Screenshot 2024-08-26 at 12 15 34" src="https://github.com/user-attachments/assets/79bdbb70-7d30-481f-b844-0261a1c88819">

**Comment by kimisgold** [comment]
That margin has been removed, and I've provided an override that should fix that misalignment in the second block.

I'm unable to see your top-border issue, using Safari, Firefox, and Chrome on macOS. Not sure what's going on there.

> I suppose you can't grey out options in the page edit based on whether you select a template, but that CSS should be overriding the vertical/horizontal differences.

Yeah, I'm not sure what kind of output one would want from vertical/horizontal layouts of this block. We also can't gray out those options with the template selected. I was going to lean on documentation to explain that.

**Comment by allanaaa** [comment]
Hrmm, that margin change seems to have fixed the 3rd issue too. 

I can't see that border line on Windows, but it's still there on my mac. Let's ignore it until it pops up elsewhere. 

I tried to break the media template by combining it with a grid layout, which was successful. I think you may have the "2 or 1 column" width measuring the whole page rather than the width of the page block? 

<img width="1299" alt="Screenshot 2024-08-26 at 17 14 23" src="https://github.com/user-attachments/assets/40e69822-dd40-4c70-b5ec-b241be9114b9">

I would think each page block would switch from 2 columns to 1 when they are are too narrow, but instead they stay 2-column forever and then the second page block in the row gets rearranged instead.

**Comment by kimisgold** [comment]
Gotcha, I've set some container queries to make this template scale for grid layout. It's ready for a look.

**Comment by allanaaa** [comment]
Great! That's working as expected. 

From my understanding: "spotlight" just makes space for the image, whether that's "left-image" or the default right. "dark-accent" and "light-accent" can be used on any block that is the full width of the page, it just changes some colours. I'm just hoping those can be used without "spotlight" also being there? It could be more flexible if you can use it to highlight any block (or block group) without it being part of the background-image bit.

**Comment by kimisgold** [comment]
The light and dark accent classes can now be used with any block. I've pushed a few more styles to accommodate things like link and border combinations with the dark accent.

**Comment by allanaaa** [comment]
That's great! I think a lot of people will find the accents handy. 
The spotlight image is a great way to spruce up some of the plainer blocks like tables of contents and page lists. I also love that you could put a Map on one side and then a historical map image from your assets on the other half. 

I just started testing on a normal flow page - with the media embed block (and the two-column class), the colours need work (because the media cards have their own colours that should be overriding this):

<img width="1492" alt="Screenshot 2024-08-31 at 15 52 47" src="https://github.com/user-attachments/assets/28ea0038-e58b-4de8-95d2-1d84804afcc1">

I'm not sure we need white text on the dark-accent to be honest. It's not that dark a background (although your a11y tests will know better than me). I prefer the black text to the white:

<img width="641" alt="Screenshot 2024-08-31 at 15 55 12" src="https://github.com/user-attachments/assets/2720db88-2efe-49e7-9e42-f2fae8101c52">
<img width="615" alt="Screenshot 2024-08-31 at 15 55 27" src="https://github.com/user-attachments/assets/7e95a345-5e06-4a77-b062-e8e0e9525868">

**Comment by allanaaa** [comment]
dark-accent should also have top and bottom padding just in case the contents are like the media embed block and have things nestled just inside. Or, I guess, we can recommend they add their own padding in the block settings?

**Comment by allanaaa** [comment]
Not surprisingly, in normal flow, a right-floated object is not playing nicely. 

With spotlight + dark-accent on, it's totally obscured - 
<img width="1317" alt="Screenshot 2024-08-31 at 16 08 34" src="https://github.com/user-attachments/assets/22fb7eaf-d707-46ef-bf3a-6e0c153c662b">
<img width="1313" alt="Screenshot 2024-08-31 at 16 08 40" src="https://github.com/user-attachments/assets/cf88c055-42cc-42a5-bf62-a8304ec2018f">

And with spotlight on and no accent - 
<img width="1375" alt="Screenshot 2024-08-31 at 16 09 50" src="https://github.com/user-attachments/assets/f3602c6c-7803-44a2-b978-0d5a7201c92c">

I don't know if you have any thoughts about how to wrap these, or if this is a lost cause?

**Comment by allanaaa** [comment]
Also a problem setting the background colour on buttons with dark-accent:

<img width="664" alt="Screenshot 2024-08-31 at 15 48 57" src="https://github.com/user-attachments/assets/2e2efa36-d71f-4481-b006-ef273478d527">


Line 487 on: 

  .dark-accent button,
  .dark-accent a.button,
  .dark-accent .resource-list.preview+a,
  .dark-accent [type=submit] {
    background-color:#ddd;
    color:#787878;
    font-weight:normal
  }

**Comment by kimisgold** [comment]
Fixed:
* Corrected text color for cards when using `.dark-accent`.
* Corrected colors for item carousel buttons within `.dark-accent` block.
* Added top and bottom padding to blocks using `.dark-accent` or `.light-accent`.
* Fixed overflow for '.dark-accent` and `.light-accent` blocks with floated children.
* Ensure `.dark-accent` and `.light-accent` clear floated elements, taking up their own line.

 > I'm not sure we need white text on the dark-accent to be honest. It's not that dark a background (although your a11y tests will know better than me). I prefer the black text to the white

Both pass accessibility tests, but admittedly I don't enjoy reading the black text on the dark accent background.

Let me know if I've missed anything.

**Comment by allanaaa** [comment]
I'm getting text overflow in anything that's both "spotlight" and "-accent" - text overflowing the "background" image from the spotlight. On a block that's just "spotlight" the text is staying where it should. 

<img width="1189" alt="Screenshot 2024-09-04 at 06 37 10" src="https://github.com/user-attachments/assets/fc9b8581-2398-4c7e-b759-5f1cb80b2e84">

(The following is two blocks side-by-side - the first with a left-image and no -accent; the second with light-accent):
<img width="1187" alt="Screenshot 2024-09-04 at 06 38 31" src="https://github.com/user-attachments/assets/2737ac78-f6a2-4b78-9926-074fc8202ad0">

**Comment by allanaaa** [comment]
In normal flow, with a right-floated element (the vertical media embed), the spotlight (without -accent) underlays its background image along the full width of the page. But the spotlight left-image seems to occupy the space and wrap the text correctly:

<img width="1286" alt="Screenshot 2024-09-04 at 06 51 47" src="https://github.com/user-attachments/assets/c4b1efdc-ebba-4368-ba09-228fdb2efafb">


The width calculations are the full page either way (it's not subtracting the float from the available space) but I guess text and "background" images behave differently. Any way to fix this?

**Comment by kimisgold** [comment]
With the floated element colliding into spotlight blocks, I think it's a simple oversight that the spotlight blocks aren't clearing floated elements. For the side by side spotlight blocks, the overflowing text was due to an accidentally overridden right padding rule. Both should be fixed now.
